version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  celery:
    build: .
    command: celery -A dashboard worker --pool=solo -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://web:8001

  celery-beat:
    build: .
    command: celery -A dashboard beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://web:8001
  
  telegram_bot:
    build: .
    command: python telegram_bot.py
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - API_BASE_URL=http://web:8001

  telegram_bot_req:
    build: .
    command: python telegram_bot_req.py
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - TELEGRAM_REQ_TOKEN=${TELEGRAM_REQ_TOKEN}
      - TARGET_GROUP_ID=${TARGET_GROUP_ID}
      - FINISHED_GROUP_ID=${FINISHED_GROUP_ID}
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env