name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add server to known_hosts (with logging)
        run: |
          echo "Пробую підключитися до ${{ secrets.HOST }} на порт 22..."
          ssh-keyscan -v -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts 2>&1 | tee ssh-keyscan.log || true
          echo "=== Вміст ssh-keyscan.log ==="
          cat ssh-keyscan.log

      - name: Deploy and restart services (Windows)
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        run: |
          ssh -i ~/.ssh/id_ed25519 $USERNAME@$HOST powershell -Command "
            cd $env:PROJECT_PATH;
            git pull origin main;
            Get-Process -Name 'python' -ErrorAction SilentlyContinue | Where-Object { $_.Path -like '*manage.py*' } | Stop-Process -Force;
            docker-compose down;
            docker-compose up -d --build;
            Start-Process -NoNewWindow -FilePath 'python' -ArgumentList 'manage.py', 'runserver', '0.0.0.0:8000'
          "